use std::{collections::BTreeSet, fs, path::PathBuf};

use serde_json::Value;

const COMMANDS: &[&str] = &[
    "verify_core_binary",
    "get_core_manifest",
    "start_core",
    "stop_core",
    "restart_core",
    "get_core_process_state",
    "get_core_stdout_tail",
    "get_core_stderr_tail",
    "open_logs_directory",
    "open_data_directory",
    "get_dashboard_snapshot",
    "lookup_explorer_address",
    "lookup_explorer_transaction",
    "save_node_config",
    "get_node_config_snapshot",
    "generate_support_package",
    "run_network_diagnostics",
    "get_mock_dashboard_snapshot",
    "get_default_paths",
];

const LINUX_MOCK_COMMANDS: &[&str] = &[
    "get_mock_dashboard_snapshot",
    "get_node_config_snapshot",
    "get_default_paths",
];

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative_path: &str) -> String {
    fs::read_to_string(manifest_dir().join(relative_path))
        .unwrap_or_else(|error| panic!("failed to read {relative_path}: {error}"))
}

fn expected_commands() -> BTreeSet<String> {
    COMMANDS
        .iter()
        .map(|command| (*command).to_string())
        .collect()
}

fn registered_commands(source: &str) -> BTreeSet<String> {
    source
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix("commands::")
                .map(|command| command.trim_end_matches(',').to_string())
        })
        .collect()
}

fn annotated_commands(source: &str) -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    let mut command_attribute_seen = false;

    for line in source.lines().map(str::trim) {
        if line == "#[tauri::command]" {
            command_attribute_seen = true;
        } else if command_attribute_seen {
            if let Some(signature) = line.strip_prefix("pub fn ") {
                let name = signature
                    .split(['(', '<'])
                    .next()
                    .expect("public command function has a name");
                commands.insert(name.to_string());
                command_attribute_seen = false;
            }
        }
    }

    assert!(
        !command_attribute_seen,
        "a #[tauri::command] attribute is not followed by a public function"
    );
    commands
}

fn app_manifest_commands(source: &str) -> BTreeSet<String> {
    let start = source
        .find("const APPLICATION_COMMANDS")
        .expect("build.rs defines APPLICATION_COMMANDS");
    let list = &source[start..];
    let end = list.find("];").expect("APPLICATION_COMMANDS is closed");

    list[..end]
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            line.strip_prefix('"')
                .and_then(|value| value.strip_suffix("\","))
                .map(str::to_string)
        })
        .collect()
}

#[test]
fn callable_commands_match_the_app_manifest_and_main_window_capability() {
    let expected = expected_commands();
    let lib_source = read("src/lib.rs");
    let command_source = read("src/commands.rs");
    let build_source = read("build.rs");

    assert_eq!(registered_commands(&lib_source), expected);
    assert_eq!(annotated_commands(&command_source), expected);
    assert_eq!(app_manifest_commands(&build_source), expected);

    let generated_directory = manifest_dir().join("permissions/autogenerated");
    let generated_commands: BTreeSet<String> = fs::read_dir(&generated_directory)
        .expect("generated application permissions directory exists")
        .map(|entry| {
            entry
                .expect("generated permission entry is readable")
                .path()
                .file_stem()
                .expect("generated permission has a file name")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    assert_eq!(generated_commands, expected);

    for command in COMMANDS {
        let permission = read(&format!("permissions/autogenerated/{command}.toml"));
        assert!(permission.contains(&format!(
            "identifier = \"allow-{}\"",
            command.replace('_', "-")
        )));
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(permission.contains(&format!(
            "identifier = \"deny-{}\"",
            command.replace('_', "-")
        )));
        assert!(permission.contains(&format!("commands.deny = [\"{command}\"]")));
    }

    let capability: Value = serde_json::from_str(&read("capabilities/main-desktop.json"))
        .expect("main Desktop capability is valid JSON");
    let capability_permissions: BTreeSet<String> = capability["permissions"]
        .as_array()
        .expect("capability permissions are an array")
        .iter()
        .map(|permission| {
            permission
                .as_str()
                .expect("permission is a string")
                .to_string()
        })
        .collect();
    let expected_permissions: BTreeSet<String> = expected
        .iter()
        .map(|command| format!("allow-{}", command.replace('_', "-")))
        .collect();

    assert_eq!(capability["identifier"], "main-desktop");
    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(capability["platforms"], serde_json::json!(["windows"]));
    assert!(capability.get("remote").is_none());
    assert_eq!(capability_permissions, expected_permissions);
    assert!(capability_permissions
        .iter()
        .all(|permission| !permission.contains(':')));
}

#[test]
fn tauri_config_selects_only_the_explicit_main_window_capability() {
    let config: Value =
        serde_json::from_str(&read("tauri.conf.json")).expect("Tauri config is valid JSON");

    assert_eq!(config["app"]["windows"].as_array().map(Vec::len), Some(1));
    assert_eq!(config["app"]["windows"][0]["label"], "main");
    assert_eq!(
        config["app"]["security"]["capabilities"],
        serde_json::json!(["main-desktop", "main-desktop-linux-mock"])
    );
}

#[test]
fn linux_mock_capability_is_read_only_and_least_privilege() {
    let capability: Value =
        serde_json::from_str(&read("capabilities/main-desktop-linux-mock.json"))
            .expect("Linux mock capability is valid JSON");
    let permissions: BTreeSet<String> = capability["permissions"]
        .as_array()
        .expect("Linux mock permissions are an array")
        .iter()
        .map(|permission| {
            permission
                .as_str()
                .expect("permission is a string")
                .to_string()
        })
        .collect();
    let expected: BTreeSet<String> = LINUX_MOCK_COMMANDS
        .iter()
        .map(|command| format!("allow-{}", command.replace('_', "-")))
        .collect();

    assert_eq!(capability["identifier"], "main-desktop-linux-mock");
    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(capability["platforms"], serde_json::json!(["linux"]));
    assert!(capability.get("remote").is_none());
    assert_eq!(permissions, expected);
    assert!(!permissions.iter().any(|permission| {
        permission.contains("start")
            || permission.contains("stop")
            || permission.contains("restart")
            || permission.contains("save")
            || permission.contains("open")
            || permission.contains("generate")
            || permission.contains("run-network")
    }));
}

#[test]
fn single_instance_is_first_and_native_plugins_remain_unpermissioned() {
    let lib_source = read("src/lib.rs");
    let capability_source = read("capabilities/main-desktop.json");

    let single_instance = lib_source
        .find(".plugin(tauri_plugin_single_instance::init(")
        .expect("single-instance plugin is initialized");
    let dialog = lib_source
        .find(".plugin(tauri_plugin_dialog::init())")
        .expect("native dialog plugin is initialized");
    let managed_state = lib_source
        .find(".manage(SupervisorState::default())")
        .expect("supervisor state is managed");
    let setup = lib_source
        .find(".setup(")
        .expect("application setup exists");
    let invoke_handler = lib_source
        .find(".invoke_handler(")
        .expect("invoke handler exists");

    assert!(single_instance < managed_state);
    assert!(single_instance < dialog);
    assert!(single_instance < setup);
    assert!(single_instance < invoke_handler);
    assert!(dialog < managed_state);
    assert!(dialog < setup);
    assert!(dialog < invoke_handler);
    assert_eq!(
        lib_source
            .match_indices(".plugin(tauri_plugin_single_instance::init(")
            .count(),
        1
    );
    assert_eq!(
        lib_source
            .match_indices(".plugin(tauri_plugin_dialog::init())")
            .count(),
        1
    );
    assert!(lib_source.contains("|app, _duplicate_arguments, _duplicate_working_directory|"));
    assert!(lib_source.contains("single_instance::activate_main_window(app);"));
    assert!(!capability_source.contains("dialog:"));
    assert!(!capability_source.contains("single-instance:"));
    assert!(!capability_source.contains("wallet"));
}

#[test]
fn duplicate_launch_data_cannot_reach_the_window_activation_handler() {
    let source = read("src/single_instance.rs");

    assert!(source.contains("pub(crate) fn activate_main_window<R: Runtime>(app: &AppHandle<R>)"));
    assert!(!source.contains("Vec<String>"));
    assert!(!source.contains("PathBuf"));
    assert!(!source.contains("current_dir"));
    assert!(!source.contains("std::env"));
    assert!(!source.contains("println!"));
    assert!(!source.contains("tracing::"));
    assert!(source.contains("app.get_webview_window(MAIN_WINDOW_LABEL)"));
    assert!(source.contains("window.show()"));
    assert!(source.contains("window.unminimize()"));
    assert!(source.contains("window.set_focus()"));
}

#[test]
fn private_wallet_runtime_has_no_tauri_or_frontend_authority() {
    let lib_source = read("src/lib.rs");
    let runtime_source = read("src/wallet/runtime.rs");
    let lifecycle_source = read("src/wallet/windows_lifecycle.rs");
    let recovery_selection_source = read("src/wallet/recovery_selection.rs");
    let wallet_adapter_source = read("src/wallet/lifecycle.rs");
    let secure_filesystem_source = read("src/wallet/secure_filesystem.rs");
    let storage_security_source = read("src/wallet/storage_security.rs");
    let vault_source = read("src/wallet/vault.rs");
    let device_protection_source = read("src/wallet/device_protection.rs");
    let secret_input_source = read("src/wallet/secret_input.rs");
    let capability_source = read("capabilities/main-desktop.json");

    assert!(lib_source.contains("wallet::WalletRuntimeState::initialize()"));
    assert!(lib_source.contains("wallet::WindowsWalletLifecycle::register("));
    assert!(lib_source.contains("WindowsWalletLifecycle::register(Arc::clone("));
    assert!(lib_source.contains("&wallet_runtime"));
    assert!(lib_source.contains("app.manage(wallet_runtime)"));
    assert!(lib_source.contains("app.manage(wallet_lifecycle)"));
    assert!(lib_source.contains("wallet::WalletLifecycleAdapters::initialize("));
    assert!(lib_source.contains("app.path().local_data_dir()"));
    let wallet_adapter_production = wallet_adapter_source
        .split("#[cfg(test)]\nmod tests")
        .next()
        .expect("wallet adapter has production source");
    assert!(!wallet_adapter_production.contains("var_os(\"LOCALAPPDATA\")"));
    assert_eq!(
        wallet_adapter_production
            .match_indices("validate_local_custody_root(")
            .count(),
        3
    );
    assert!(wallet_adapter_source.contains("GetDriveTypeW"));
    assert!(wallet_adapter_source.contains("FILE_ATTRIBUTE_REPARSE_POINT"));
    assert!(lib_source.contains("app.manage(wallet_adapters)"));
    assert!(lib_source.contains("runtime.invalidate_all()"));
    assert!(!runtime_source.contains("#[tauri::command]"));
    assert!(!lifecycle_source.contains("#[tauri::command]"));
    assert!(!lifecycle_source.contains("AppHandle"));
    assert!(lifecycle_source.contains("WTSRegisterSessionNotification"));
    assert!(lifecycle_source.contains("WM_WTSSESSION_CHANGE"));
    assert!(lifecycle_source.contains("WM_POWERBROADCAST"));
    assert!(lifecycle_source.contains("WM_QUERYENDSESSION"));
    assert!(lifecycle_source.contains("runtime.invalidate_all()"));
    assert!(!recovery_selection_source.contains("#[tauri::command]"));
    assert!(!wallet_adapter_source.contains("#[tauri::command]"));
    assert!(!secure_filesystem_source.contains("#[tauri::command]"));
    assert!(secure_filesystem_source.contains("FILE_FLAG_OPEN_REPARSE_POINT"));
    assert!(secure_filesystem_source.contains("SetFileInformationByHandle"));
    assert!(secure_filesystem_source.contains("FileRenameInfo"));
    assert!(secure_filesystem_source.contains(".share_mode(FILE_SHARE_READ)"));
    assert!(secure_filesystem_source.contains("share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE)"));
    assert!(storage_security_source.contains("SetSecurityInfo"));
    assert!(storage_security_source.contains("GetSecurityInfo"));
    assert!(vault_source.contains("storage_security::protect_open_file(&temporary)"));
    assert!(vault_source.contains("publish_open_file(&temporary, path)"));
    assert!(!vault_source.contains("fs::rename(&temporary_path, path)"));
    assert!(device_protection_source.contains("windows_dpapi_current_user"));
    assert!(!device_protection_source.contains("CRYPTPROTECT_LOCAL_MACHINE"));
    assert!(!wallet_adapter_source.contains("tauri::Window"));
    assert!(!wallet_adapter_source.contains("AppHandle"));
    assert!(wallet_adapter_source.contains("begin_operation"));
    assert!(wallet_adapter_source.contains("consume_recovery_path"));
    assert!(wallet_adapter_source.contains("ensure_current"));
    assert!(!recovery_selection_source.contains("into_path()"));
    assert!(recovery_selection_source.contains("Some(FilePath::Path(path))"));
    assert!(recovery_selection_source.contains(".set_parent(window)"));
    assert!(recovery_selection_source.contains("FILE_ATTRIBUTE_REPARSE_POINT"));
    assert!(recovery_selection_source.contains("begin_recovery_path_selection"));
    assert!(recovery_selection_source.contains("complete_recovery_path_selection"));
    assert!(recovery_selection_source.contains("cancel_recovery_path_selection"));
    assert!(!secret_input_source.contains("#[tauri::command]"));
    assert!(!secret_input_source.contains("impl Serialize"));
    assert!(!secret_input_source.contains("#[derive("));
    assert!(!secret_input_source.contains("impl Clone"));
    assert!(!secret_input_source.contains("impl fmt::Debug"));
    assert!(!capability_source.contains("wallet"));
    assert!(!capability_source.contains("dialog:"));
    assert!(!read("../src/services/coreApi.ts").contains("wallet_"));
    assert!(!read("../package.json").contains("@tauri-apps/plugin-dialog"));
}
