use std::{collections::BTreeSet, fs, path::PathBuf};

use serde_json::Value;

const COMMANDS: &[&str] = &[
    "verify_core_binary",
    "get_core_manifest",
    "start_core",
    "stop_core",
    "restart_core",
    "get_core_process_state",
    "get_core_stdout_tail",
    "get_core_stderr_tail",
    "open_logs_directory",
    "open_data_directory",
    "get_dashboard_snapshot",
    "lookup_explorer_address",
    "lookup_explorer_transaction",
    "save_node_config",
    "get_node_config_snapshot",
    "generate_support_package",
    "run_network_diagnostics",
    "get_mock_dashboard_snapshot",
    "get_default_paths",
];

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative_path: &str) -> String {
    fs::read_to_string(manifest_dir().join(relative_path))
        .unwrap_or_else(|error| panic!("failed to read {relative_path}: {error}"))
}

fn expected_commands() -> BTreeSet<String> {
    COMMANDS
        .iter()
        .map(|command| (*command).to_string())
        .collect()
}

fn registered_commands(source: &str) -> BTreeSet<String> {
    source
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix("commands::")
                .map(|command| command.trim_end_matches(',').to_string())
        })
        .collect()
}

fn annotated_commands(source: &str) -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    let mut command_attribute_seen = false;

    for line in source.lines().map(str::trim) {
        if line == "#[tauri::command]" {
            command_attribute_seen = true;
        } else if command_attribute_seen {
            if let Some(signature) = line.strip_prefix("pub fn ") {
                let name = signature
                    .split(['(', '<'])
                    .next()
                    .expect("public command function has a name");
                commands.insert(name.to_string());
                command_attribute_seen = false;
            }
        }
    }

    assert!(
        !command_attribute_seen,
        "a #[tauri::command] attribute is not followed by a public function"
    );
    commands
}

fn app_manifest_commands(source: &str) -> BTreeSet<String> {
    let start = source
        .find("const APPLICATION_COMMANDS")
        .expect("build.rs defines APPLICATION_COMMANDS");
    let list = &source[start..];
    let end = list.find("];").expect("APPLICATION_COMMANDS is closed");

    list[..end]
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            line.strip_prefix('"')
                .and_then(|value| value.strip_suffix("\","))
                .map(str::to_string)
        })
        .collect()
}

#[test]
fn callable_commands_match_the_app_manifest_and_main_window_capability() {
    let expected = expected_commands();
    let lib_source = read("src/lib.rs");
    let command_source = read("src/commands.rs");
    let build_source = read("build.rs");

    assert_eq!(registered_commands(&lib_source), expected);
    assert_eq!(annotated_commands(&command_source), expected);
    assert_eq!(app_manifest_commands(&build_source), expected);

    let generated_directory = manifest_dir().join("permissions/autogenerated");
    let generated_commands: BTreeSet<String> = fs::read_dir(&generated_directory)
        .expect("generated application permissions directory exists")
        .map(|entry| {
            entry
                .expect("generated permission entry is readable")
                .path()
                .file_stem()
                .expect("generated permission has a file name")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    assert_eq!(generated_commands, expected);

    for command in COMMANDS {
        let permission = read(&format!("permissions/autogenerated/{command}.toml"));
        assert!(permission.contains(&format!(
            "identifier = \"allow-{}\"",
            command.replace('_', "-")
        )));
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(permission.contains(&format!(
            "identifier = \"deny-{}\"",
            command.replace('_', "-")
        )));
        assert!(permission.contains(&format!("commands.deny = [\"{command}\"]")));
    }

    let capability: Value = serde_json::from_str(&read("capabilities/main-desktop.json"))
        .expect("main Desktop capability is valid JSON");
    let capability_permissions: BTreeSet<String> = capability["permissions"]
        .as_array()
        .expect("capability permissions are an array")
        .iter()
        .map(|permission| {
            permission
                .as_str()
                .expect("permission is a string")
                .to_string()
        })
        .collect();
    let expected_permissions: BTreeSet<String> = expected
        .iter()
        .map(|command| format!("allow-{}", command.replace('_', "-")))
        .collect();

    assert_eq!(capability["identifier"], "main-desktop");
    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(capability["platforms"], serde_json::json!(["windows"]));
    assert!(capability.get("remote").is_none());
    assert_eq!(capability_permissions, expected_permissions);
    assert!(capability_permissions
        .iter()
        .all(|permission| !permission.contains(':')));
}

#[test]
fn tauri_config_selects_only_the_explicit_main_window_capability() {
    let config: Value =
        serde_json::from_str(&read("tauri.conf.json")).expect("Tauri config is valid JSON");

    assert_eq!(config["app"]["windows"].as_array().map(Vec::len), Some(1));
    assert_eq!(config["app"]["windows"][0]["label"], "main");
    assert_eq!(
        config["app"]["security"]["capabilities"],
        serde_json::json!(["main-desktop"])
    );
}

#[test]
fn pinned_wallet_plugins_remain_uninitialized_and_unpermissioned() {
    let lib_source = read("src/lib.rs");
    let capability_source = read("capabilities/main-desktop.json");

    assert!(!lib_source.contains("tauri_plugin_dialog"));
    assert!(!lib_source.contains("tauri_plugin_single_instance"));
    assert!(!capability_source.contains("dialog:"));
    assert!(!capability_source.contains("single-instance:"));
    assert!(!capability_source.contains("wallet"));
}
