use std::{collections::BTreeSet, fs, path::PathBuf};

use serde_json::Value;

const COMMANDS: &[&str] = &[
    "verify_core_binary",
    "get_core_manifest",
    "start_core",
    "stop_core",
    "restart_core",
    "get_core_process_state",
    "get_core_stdout_tail",
    "get_core_stderr_tail",
    "open_logs_directory",
    "open_data_directory",
    "get_dashboard_snapshot",
    "lookup_explorer_address",
    "lookup_explorer_transaction",
    "save_node_config",
    "get_node_config_snapshot",
    "generate_support_package",
    "run_network_diagnostics",
    "get_mock_dashboard_snapshot",
    "get_default_paths",
    "wallet_get_status",
    "wallet_select_recovery_destination",
    "wallet_create",
    "wallet_select_recovery_source",
    "wallet_restore",
    "wallet_unlock",
    "wallet_lock",
    "wallet_prepare_transfer_preview",
    "wallet_cancel_transfer_preview",
    "wallet_confirm_and_submit_transfer",
    "wallet_list_activity",
    "wallet_refresh_transaction_observation",
];

const WALLET_COMMANDS: &[&str] = &[
    "wallet_get_status",
    "wallet_select_recovery_destination",
    "wallet_create",
    "wallet_select_recovery_source",
    "wallet_restore",
    "wallet_unlock",
    "wallet_lock",
    "wallet_prepare_transfer_preview",
    "wallet_cancel_transfer_preview",
    "wallet_confirm_and_submit_transfer",
    "wallet_list_activity",
    "wallet_refresh_transaction_observation",
];

const LINUX_MOCK_COMMANDS: &[&str] = &[
    "get_mock_dashboard_snapshot",
    "get_node_config_snapshot",
    "get_default_paths",
];

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn read(relative_path: &str) -> String {
    fs::read_to_string(manifest_dir().join(relative_path))
        .unwrap_or_else(|error| panic!("failed to read {relative_path}: {error}"))
        .replace("\r\n", "\n")
}

fn expected_commands() -> BTreeSet<String> {
    COMMANDS
        .iter()
        .map(|command| (*command).to_string())
        .collect()
}

fn registered_commands(source: &str) -> BTreeSet<String> {
    source
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            line.strip_prefix("commands::")
                .or_else(|| line.strip_prefix("wallet::exposure::"))
                .map(|command| command.trim_end_matches(',').to_string())
        })
        .collect()
}

fn annotated_commands(source: &str) -> BTreeSet<String> {
    let mut commands = BTreeSet::new();
    let mut command_attribute_seen = false;

    for line in source.lines().map(str::trim) {
        if line == "#[tauri::command]" {
            command_attribute_seen = true;
        } else if command_attribute_seen {
            let signature = line
                .strip_prefix("pub fn ")
                .or_else(|| line.strip_prefix("pub async fn "))
                .or_else(|| line.strip_prefix("pub(crate) fn "))
                .or_else(|| line.strip_prefix("pub(crate) async fn "));
            if let Some(signature) = signature {
                let name = signature
                    .split(['(', '<'])
                    .next()
                    .expect("public command function has a name");
                commands.insert(name.to_string());
                command_attribute_seen = false;
            }
        }
    }

    assert!(
        !command_attribute_seen,
        "a #[tauri::command] attribute is not followed by a public function"
    );
    commands
}

fn app_manifest_commands(source: &str) -> BTreeSet<String> {
    let start = source
        .find("const APPLICATION_COMMANDS")
        .expect("build.rs defines APPLICATION_COMMANDS");
    let list = &source[start..];
    let end = list.find("];").expect("APPLICATION_COMMANDS is closed");

    list[..end]
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            line.strip_prefix('"')
                .and_then(|value| value.strip_suffix("\","))
                .map(str::to_string)
        })
        .collect()
}

#[test]
fn callable_commands_match_the_app_manifest_and_main_window_capability() {
    let expected = expected_commands();
    let lib_source = read("src/lib.rs");
    let command_source = read("src/commands.rs");
    let wallet_command_source = read("src/wallet/exposure.rs");
    let build_source = read("build.rs");

    assert_eq!(registered_commands(&lib_source), expected);
    let annotated: BTreeSet<String> = annotated_commands(&command_source)
        .into_iter()
        .chain(annotated_commands(&wallet_command_source))
        .collect();
    assert_eq!(annotated, expected);
    assert_eq!(app_manifest_commands(&build_source), expected);

    let generated_directory = manifest_dir().join("permissions/autogenerated");
    let generated_commands: BTreeSet<String> = fs::read_dir(&generated_directory)
        .expect("generated application permissions directory exists")
        .map(|entry| {
            entry
                .expect("generated permission entry is readable")
                .path()
                .file_stem()
                .expect("generated permission has a file name")
                .to_string_lossy()
                .into_owned()
        })
        .collect();
    assert_eq!(generated_commands, expected);

    for command in COMMANDS {
        let permission = read(&format!("permissions/autogenerated/{command}.toml"));
        assert!(permission.contains(&format!(
            "identifier = \"allow-{}\"",
            command.replace('_', "-")
        )));
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(permission.contains(&format!(
            "identifier = \"deny-{}\"",
            command.replace('_', "-")
        )));
        assert!(permission.contains(&format!("commands.deny = [\"{command}\"]")));
    }

    let capability: Value = serde_json::from_str(&read("capabilities/main-desktop.json"))
        .expect("main Desktop capability is valid JSON");
    let capability_permissions: BTreeSet<String> = capability["permissions"]
        .as_array()
        .expect("capability permissions are an array")
        .iter()
        .map(|permission| {
            permission
                .as_str()
                .expect("permission is a string")
                .to_string()
        })
        .collect();
    let expected_permissions: BTreeSet<String> = expected
        .iter()
        .map(|command| format!("allow-{}", command.replace('_', "-")))
        .collect();

    assert_eq!(capability["identifier"], "main-desktop");
    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(capability["platforms"], serde_json::json!(["windows"]));
    assert!(capability.get("remote").is_none());
    assert_eq!(capability_permissions, expected_permissions);
    assert!(capability_permissions
        .iter()
        .all(|permission| !permission.contains(':')));
}

#[test]
fn tauri_config_selects_only_the_explicit_main_window_capability() {
    let config: Value =
        serde_json::from_str(&read("tauri.conf.json")).expect("Tauri config is valid JSON");

    assert_eq!(config["app"]["windows"].as_array().map(Vec::len), Some(1));
    assert_eq!(config["app"]["windows"][0]["label"], "main");
    assert_eq!(
        config["app"]["security"]["capabilities"],
        serde_json::json!(["main-desktop", "main-desktop-linux-mock"])
    );
}

#[test]
fn linux_mock_capability_is_read_only_and_least_privilege() {
    let capability: Value =
        serde_json::from_str(&read("capabilities/main-desktop-linux-mock.json"))
            .expect("Linux mock capability is valid JSON");
    let permissions: BTreeSet<String> = capability["permissions"]
        .as_array()
        .expect("Linux mock permissions are an array")
        .iter()
        .map(|permission| {
            permission
                .as_str()
                .expect("permission is a string")
                .to_string()
        })
        .collect();
    let expected: BTreeSet<String> = LINUX_MOCK_COMMANDS
        .iter()
        .map(|command| format!("allow-{}", command.replace('_', "-")))
        .collect();

    assert_eq!(capability["identifier"], "main-desktop-linux-mock");
    assert_eq!(capability["windows"], serde_json::json!(["main"]));
    assert_eq!(capability["platforms"], serde_json::json!(["linux"]));
    assert!(capability.get("remote").is_none());
    assert_eq!(permissions, expected);
    assert!(!permissions.iter().any(|permission| {
        permission.contains("start")
            || permission.contains("stop")
            || permission.contains("restart")
            || permission.contains("save")
            || permission.contains("open")
            || permission.contains("generate")
            || permission.contains("run-network")
    }));
}

#[test]
fn single_instance_is_first_and_native_plugins_remain_unpermissioned() {
    let lib_source = read("src/lib.rs");
    let capability_source = read("capabilities/main-desktop.json");

    let single_instance = lib_source
        .find(".plugin(tauri_plugin_single_instance::init(")
        .expect("single-instance plugin is initialized");
    let dialog = lib_source
        .find(".plugin(tauri_plugin_dialog::init())")
        .expect("native dialog plugin is initialized");
    let managed_state = lib_source
        .find(".manage(Arc::new(SupervisorState::default()))")
        .expect("supervisor state is managed");
    let setup = lib_source
        .find(".setup(")
        .expect("application setup exists");
    let invoke_handler = lib_source
        .find(".invoke_handler(")
        .expect("invoke handler exists");

    assert!(single_instance < managed_state);
    assert!(single_instance < dialog);
    assert!(single_instance < setup);
    assert!(single_instance < invoke_handler);
    assert!(dialog < managed_state);
    assert!(dialog < setup);
    assert!(dialog < invoke_handler);
    assert_eq!(
        lib_source
            .match_indices(".plugin(tauri_plugin_single_instance::init(")
            .count(),
        1
    );
    assert_eq!(
        lib_source
            .match_indices(".plugin(tauri_plugin_dialog::init())")
            .count(),
        1
    );
    assert!(lib_source.contains("|app, _duplicate_arguments, _duplicate_working_directory|"));
    assert!(lib_source.contains("single_instance::activate_main_window(app);"));
    assert!(!capability_source.contains("dialog:"));
    assert!(!capability_source.contains("single-instance:"));
    assert_eq!(
        capability_source.match_indices("allow-wallet-").count(),
        WALLET_COMMANDS.len()
    );
}

#[test]
fn duplicate_launch_data_cannot_reach_the_window_activation_handler() {
    let source = read("src/single_instance.rs");

    assert!(source.contains("pub(crate) fn activate_main_window<R: Runtime>(app: &AppHandle<R>)"));
    assert!(!source.contains("Vec<String>"));
    assert!(!source.contains("PathBuf"));
    assert!(!source.contains("current_dir"));
    assert!(!source.contains("std::env"));
    assert!(!source.contains("println!"));
    assert!(!source.contains("tracing::"));
    assert!(source.contains("app.get_webview_window(MAIN_WINDOW_LABEL)"));
    assert!(source.contains("window.show()"));
    assert!(source.contains("window.unminimize()"));
    assert!(source.contains("window.set_focus()"));
}

#[test]
fn atomic_wallet_surface_preserves_private_custody_authority() {
    let lib_source = read("src/lib.rs");
    let command_source = read("src/commands.rs");
    let report_source = read("src/reports.rs");
    let runtime_source = read("src/wallet/runtime.rs");
    let lifecycle_source = read("src/wallet/windows_lifecycle.rs");
    let recovery_selection_source = read("src/wallet/recovery_selection.rs");
    let wallet_adapter_source = read("src/wallet/lifecycle.rs");
    let wallet_command_boundary_source = read("src/wallet/lifecycle_command_boundary.rs");
    let wallet_exposure_source = read("src/wallet/exposure.rs");
    let layer_a_qualification_source =
        read("src/wallet/lifecycle_command_boundary/generated_wrapper_qualification.rs");
    let layer_b_source = read("qualification/wallet-layer-b/main.rs");
    let layer_b_config = read("qualification/wallet-layer-b/tauri.conf.json");
    let layer_b_permissions = read("qualification/wallet-layer-b/permissions/wallet-layer-b.toml");
    let layer_b_page = read("qualification/wallet-layer-b/assets/index.html");
    let layer_b_script = read("qualification/wallet-layer-b/assets/harness.js");
    let layer_b_runner = read("qualification/wallet-layer-b/run-layer-b-qualification.ps1");
    let product_config = read("tauri.conf.json");
    let cargo_manifest = read("Cargo.toml");
    let build_source = read("build.rs");
    let secure_filesystem_source = read("src/wallet/secure_filesystem.rs");
    let storage_security_source = read("src/wallet/storage_security.rs");
    let vault_source = read("src/wallet/vault.rs");
    let device_protection_source = read("src/wallet/device_protection.rs");
    let secret_input_source = read("src/wallet/secret_input.rs");
    let secrets_source = read("src/wallet/secrets.rs");
    let ceremony_source = read("src/wallet/recovery_ceremony.rs");
    let ceremony_production = ceremony_source
        .split("#[cfg(test)]")
        .next()
        .expect("native ceremony module has production source");
    let panic_policy_source = read("src/wallet/panic_policy.rs");
    let public_request_source = read("src/wallet/public_request.rs");
    let public_request_production = public_request_source
        .split("#[cfg(test)]")
        .next()
        .expect("public request module has production source");
    let capability_source = read("capabilities/main-desktop.json");

    assert!(lib_source.contains("wallet::WalletRuntimeState::initialize()"));
    let panic_policy = lib_source
        .find("wallet::install_production_panic_policy()")
        .expect("silent panic policy is installed");
    let wallet_runtime_initialization = lib_source
        .find("wallet::WalletRuntimeState::initialize()")
        .expect("wallet runtime is initialized");
    assert!(panic_policy < wallet_runtime_initialization);
    let panic_policy_production = panic_policy_source
        .split("#[cfg(test)]")
        .next()
        .expect("panic policy has production source");
    assert!(panic_policy_production.contains("std::panic::set_hook"));
    assert!(!panic_policy_production.contains("eprintln!"));
    assert!(!panic_policy_production.contains("println!"));
    assert!(!panic_policy_production.contains("format!("));
    assert!(lib_source.contains("wallet::WindowsWalletLifecycle::register("));
    assert!(lib_source.contains("WindowsWalletLifecycle::register(Arc::clone("));
    assert!(lib_source.contains("&wallet_runtime"));
    assert!(lib_source.contains("app.manage(Arc::clone(&wallet_runtime))"));
    assert!(lib_source.contains("app.manage(wallet_lifecycle)"));
    assert!(lib_source.contains("wallet::WalletLifecycleAdapters::initialize("));
    assert!(lib_source.contains("wallet::NativeWalletSecretCeremony::new("));
    assert!(lib_source.contains("app.path().local_data_dir()"));
    let wallet_adapter_production = wallet_adapter_source
        .split("#[cfg(test)]\nmod tests")
        .next()
        .expect("wallet adapter has production source");
    assert!(!wallet_adapter_production.contains("var_os(\"LOCALAPPDATA\")"));
    assert_eq!(
        wallet_adapter_production
            .match_indices("validate_local_custody_root(")
            .count(),
        3
    );
    assert!(wallet_adapter_source.contains("GetDriveTypeW"));
    assert!(wallet_adapter_source.contains("FILE_ATTRIBUTE_REPARSE_POINT"));
    assert!(lib_source.contains("WalletCommandState::initialize("));
    assert!(lib_source.contains("app.manage(wallet_commands)"));
    assert!(lib_source.contains("runtime.invalidate_all()"));
    let runtime_production = runtime_source
        .split("#[cfg(test)]\nmod tests")
        .next()
        .expect("wallet runtime has production source");
    assert!(runtime_production.contains(
        "const WALLET_PROCESS_MUTEX_BASE: &str = \"com.vision.desktop.wallet-runtime.v2\""
    ));
    assert!(runtime_production.contains("\"Global\\\\{base_name}.{}\""));
    assert!(runtime_production.contains("storage_security::current_user_sid_string()"));
    assert!(runtime_production.contains("SECURITY_ATTRIBUTES"));
    assert!(runtime_production.contains("bInheritHandle: 0"));
    assert!(runtime_production.contains("D:P(A;;GA;;;{user_sid})"));
    assert!(runtime_production.contains("ERROR_ALREADY_EXISTS"));
    assert!(!runtime_production.contains("ReleaseMutex"));
    assert!(runtime_production.contains("revocation_epoch: AtomicU64"));
    assert!(runtime_production.contains("pending_revocations: AtomicU64"));
    assert!(runtime_production.contains("fn revocation_is_pending"));
    assert!(runtime_production.contains("pending_revocations.fetch_add(1, Ordering::AcqRel)"));
    assert!(runtime_production.contains("pending_revocations.fetch_sub(1, Ordering::AcqRel)"));
    assert!(runtime_production.contains("fetch_add(1, Ordering::AcqRel)"));
    assert!(runtime_production.contains("fn run_authorized<T, E>"));
    assert!(runtime_production.contains("fn complete<T>"));
    assert!(!runtime_production.contains("fn activation_proof"));
    assert!(!runtime_source.contains("#[tauri::command]"));
    assert!(!lifecycle_source.contains("#[tauri::command]"));
    assert!(!lifecycle_source.contains("AppHandle"));
    assert!(lifecycle_source.contains("WTSRegisterSessionNotification"));
    assert!(lifecycle_source.contains("WM_WTSSESSION_CHANGE"));
    assert!(lifecycle_source.contains("WM_POWERBROADCAST"));
    assert!(lifecycle_source.contains("WM_QUERYENDSESSION"));
    assert!(lifecycle_source.contains("runtime.invalidate_all()"));
    assert!(!recovery_selection_source.contains("#[tauri::command]"));
    assert!(!wallet_adapter_source.contains("#[tauri::command]"));
    assert!(!wallet_command_boundary_source.contains("#[tauri::command]"));
    assert!(wallet_command_boundary_source.contains("impl<'a, R: Runtime> CommandArg<'a, R>"));
    assert!(wallet_command_boundary_source.contains("command.message.payload()"));
    assert!(wallet_command_boundary_source.contains("command.message.command()"));
    assert!(wallet_command_boundary_source.contains("InvokeBody::Raw"));
    assert!(wallet_command_boundary_source.contains("object.is_empty()"));
    assert!(wallet_command_boundary_source.contains("object.len() != 1"));
    assert!(wallet_command_boundary_source.contains("duplicate_key_rejection_proven: true"));
    assert!(wallet_command_boundary_source.contains("WalletExposureAuthority"));
    assert!(wallet_command_boundary_source.contains("MainWalletWindowAuthority"));
    assert!(wallet_command_boundary_source.contains("BUNDLED_WINDOWS_ORIGIN"));
    assert!(wallet_command_boundary_source.contains("BoundaryFailClosedGuard"));
    assert!(!wallet_command_boundary_source.contains("derive(Debug, Serialize"));
    assert!(!wallet_command_boundary_source.contains("impl Clone for WalletExposureAuthority"));
    assert!(!wallet_command_boundary_source.contains("impl Clone for MainWalletWindowAuthority"));
    assert!(!wallet_command_boundary_source.contains("pub struct WalletExposureAuthority"));
    assert!(!wallet_command_boundary_source.contains("pub struct MainWalletWindowAuthority"));
    assert!(wallet_command_boundary_source
        .contains("#[cfg(all(test, feature = \"wallet-layer-a-qualification\"))]"));
    assert_eq!(
        layer_a_qualification_source
            .match_indices("#[tauri::command]")
            .count(),
        7
    );
    for command in [
        "fn wallet_get_status(",
        "fn wallet_select_recovery_destination(",
        "fn wallet_create(",
        "fn wallet_select_recovery_source(",
        "fn wallet_restore(",
        "fn wallet_unlock(",
        "fn wallet_lock(",
    ] {
        assert!(layer_a_qualification_source.contains(command));
    }
    assert!(layer_a_qualification_source.contains("tauri::generate_handler!["));
    assert!(layer_a_qualification_source.contains("mock_builder()"));
    assert!(layer_a_qualification_source.contains("tauri::test::get_ipc_response("));
    assert!(layer_a_qualification_source.contains("MockRuntime"));
    assert!(layer_a_qualification_source.contains("policy.duplicate_key_rejection_proven"));
    for forbidden in [
        "WalletRuntimeState",
        "WalletLifecycleAdapters",
        "SecretInput",
        "WalletSeed",
        "CoreConnectionAuthority",
        "SignedTransferArtifact",
        "AppManifest",
    ] {
        assert!(!layer_a_qualification_source.contains(forbidden));
    }
    assert!(cargo_manifest.contains("wallet-layer-a-qualification = []"));
    assert!(cargo_manifest.contains("tauri = { version = \"=2.11.5\", features = [\"test\"] }"));
    assert!(build_source.contains("CARGO_FEATURE_WALLET_LAYER_A_QUALIFICATION"));
    assert!(build_source.contains("embed_resource::compile_for_everything("));
    assert!(build_source.contains("WindowsAttributes::new_without_app_manifest()"));
    assert!(!build_source.contains("/MANIFESTINPUT:"));
    assert!(!build_source.contains("/MANIFEST:EMBED"));
    assert!(cargo_manifest.contains("wallet-layer-b-qualification = []"));
    assert!(cargo_manifest.contains("name = \"vision-wallet-transport-qualification\""));
    assert!(cargo_manifest.contains("required-features = [\"wallet-layer-b-qualification\"]"));
    assert!(build_source.contains("CARGO_FEATURE_WALLET_LAYER_B_QUALIFICATION"));
    assert!(build_source.contains("\"qualification/wallet-layer-b/permissions/*.toml\""));
    assert!(!build_source.contains("QUALIFICATION_APPLICATION_COMMANDS"));
    assert_eq!(
        layer_b_source
            .match_indices("qualification_command!(")
            .count(),
        7
    );
    for command in [
        "wallet_get_status",
        "wallet_select_recovery_destination",
        "wallet_create",
        "wallet_select_recovery_source",
        "wallet_restore",
        "wallet_unlock",
        "wallet_lock",
    ] {
        assert!(layer_b_source.contains(command));
    }
    assert!(layer_b_source.contains("QualificationInvokeRequest"));
    assert!(layer_b_source.contains("qualification_invoke_handler"));
    assert_eq!(layer_b_source.match_indices("__cmd__wallet_").count(), 14);
    assert!(layer_b_source.contains("QUALIFICATION_ARGUMENT"));
    assert!(layer_b_source.contains("Layer B qualification mode was not explicitly requested"));
    assert!(layer_b_source.contains("QUALIFICATION_WINDOW"));
    assert!(layer_b_source.contains("QUALIFICATION_HOST"));
    assert!(layer_b_source.contains("InvokeBody::Raw"));
    assert!(layer_b_source.contains("FailClosedGuard"));
    assert!(layer_b_source.contains("framework_route(request.headers, state.invoke_key())"));
    assert!(layer_b_source.contains("custom_protocol_proven"));
    assert!(layer_b_source.contains("post_message_proven"));
    assert!(layer_b_source.contains("transport_route_inconclusive"));
    assert!(layer_b_source.contains("qualification_transport_inconclusive"));
    assert!(layer_b_source.contains("layer_b_terminal_observation"));
    assert!(layer_b_source.contains("REPORT_PROTOCOL"));
    assert!(layer_b_source.contains("CONTROL_PROTOCOL"));
    assert!(layer_b_source.contains("window_authority_matches"));
    assert!(layer_b_source.contains("window-recreated-main--"));
    assert!(layer_b_source.contains("window-reloaded-generation--"));
    assert!(layer_b_source.contains("window-destruction-race--"));
    assert!(layer_b_source.contains("window-revocation-race--"));
    assert!(!layer_b_source.contains("top_level_keys"));
    assert!(!layer_b_source.contains("keys: Vec<String>"));
    assert_eq!(layer_b_source.match_indices("guard.commit()").count(), 2);
    for forbidden in [
        "vision_desktop_lib",
        "WalletRuntimeState",
        "WalletLifecycleAdapters",
        "WalletSeed",
        "SecretInput",
        "CoreConnectionAuthority",
        "SignedTransferArtifact",
        "WalletSubmission",
    ] {
        assert!(!layer_b_source.contains(forbidden));
    }
    assert!(layer_b_config.contains("com.vision.desktop.wallet-transport-qualification"));
    assert!(layer_b_config.contains("wallet-transport-qualification"));
    assert!(layer_b_config.contains("\"active\": false"));
    assert!(layer_b_config.contains("\"local\": true"));
    assert_eq!(
        layer_b_permissions.match_indices("[[permission]]").count(),
        7
    );
    for command in [
        "wallet_get_status",
        "wallet_select_recovery_destination",
        "wallet_create",
        "wallet_select_recovery_source",
        "wallet_restore",
        "wallet_unlock",
        "wallet_lock",
    ] {
        assert!(layer_b_permissions.contains(&format!("commands.allow = [\"{command}\"]")));
        assert!(manifest_dir()
            .join("permissions/autogenerated")
            .join(format!("{command}.toml"))
            .exists());
    }
    assert!(!product_config.contains("wallet-transport-qualification"));
    assert!(!product_config.contains("wallet-layer-b-qualification"));
    assert!(layer_b_page.contains("TEST-ONLY NON-CUSTODY HARNESS"));
    assert!(layer_b_script.contains("official-invoke"));
    assert!(layer_b_script.contains("internals-invoke"));
    assert!(layer_b_script.contains("internals-ipc"));
    assert!(layer_b_script.contains("internals-post-message"));
    assert!(layer_b_script.contains("directFetchProbe"));
    assert!(layer_b_script.contains("directXhrProbe"));
    assert!(layer_b_script.contains("duplicateFamilies"));
    assert!(layer_b_script.contains("nestedDuplicateFamilies"));
    assert!(layer_b_script.contains("PUBLIC_LAYER_B_CANARY"));
    assert!(layer_b_script.contains("PUBLIC_SECRET_KEY_NAME_CANARY"));
    assert!(layer_b_script.contains("postRevocationProof"));
    assert!(layer_b_script.contains("qualification-report"));
    assert!(layer_b_script.contains("qualification-control"));
    assert!(layer_b_script.contains("fallbackIntercepted"));
    assert!(layer_b_script.contains("matrix_inconclusive"));
    assert!(layer_b_script.contains("runConcurrentBatch"));
    assert!(layer_b_script.contains("Promise.allSettled(pending)"));
    assert!(layer_b_source.contains("BrowserVersionString"));
    assert!(layer_b_source.contains("loaded_webview2_version"));
    assert!(layer_b_source.contains("NativeDestructionObservation"));
    assert!(layer_b_source.contains("native_hwnd_absent"));
    assert!(layer_b_source.contains("native_destruction_records"));
    assert!(layer_b_source.contains("structural_post_revocation_proven"));
    assert!(layer_b_source.contains("valid_native_destruction_request"));
    assert!(layer_b_source.contains("mismatch_declared_command"));
    assert!(layer_b_script.contains("appendGeneratedWrapperCases"));
    assert!(layer_b_script.contains("sequential-repeat"));
    assert!(layer_b_script.contains("reordered-invoke"));
    assert!(layer_b_script.contains("declared-invoked-mismatch"));
    assert!(layer_b_script.contains("text/plain;charset=UTF-8"));
    assert!(layer_b_runner.contains("Wait-QualificationProcess"));
    assert!(layer_b_runner.contains("$Process.Kill()"));
    assert!(layer_b_runner.contains("runner-flush-proof"));
    assert!(!layer_b_runner.contains(".Kill($true)"));
    assert!(layer_b_script.contains("duplicateFamilies('wallet_create')"));
    assert!(layer_b_script.contains("['wallet_create', 'wallet_restore']"));
    assert!(layer_b_runner.contains("Start-Process"));
    assert!(layer_b_runner.contains("--wallet-layer-b-case=$case"));
    assert!(layer_b_runner.contains("stdout_sha256"));
    assert!(layer_b_runner.contains("stderr_sha256"));
    assert!(layer_b_runner.contains("'Inconclusive'"));
    assert!(layer_b_runner.contains("Test-Transcript"));
    assert!(layer_b_runner.contains("layer_b_terminal_observation"));
    assert!(layer_b_runner.contains("Get-WebView2Provenance"));
    assert!(layer_b_runner.contains("Get-FrameworkProvenance"));
    assert!(layer_b_runner.contains("Get-HarnessSourceHashes"));
    assert!(layer_b_runner.contains("Get-TreeFingerprint"));
    assert!(layer_b_runner.contains("ProductionExecutablePath"));
    assert!(layer_b_runner.contains("ProductionInstallationRoot"));
    assert!(layer_b_runner.contains("ProductionDataRoot"));
    assert!(layer_b_runner.contains("actual_loaded_webview2_runtime_proven"));
    assert!(!layer_b_script.contains("seed phrase"));
    assert!(!layer_b_script.contains("private key"));
    assert!(!secure_filesystem_source.contains("#[tauri::command]"));
    assert!(secure_filesystem_source.contains("FILE_FLAG_OPEN_REPARSE_POINT"));
    assert!(secure_filesystem_source.contains("SetFileInformationByHandle"));
    assert!(secure_filesystem_source.contains("FileRenameInfo"));
    assert!(secure_filesystem_source.contains(".share_mode(FILE_SHARE_READ)"));
    assert!(secure_filesystem_source.contains("share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE)"));
    assert!(storage_security_source.contains("SetSecurityInfo"));
    assert!(storage_security_source.contains("GetSecurityInfo"));
    assert!(vault_source.contains("storage_security::protect_open_file(&temporary)"));
    assert!(vault_source.contains("publish_open_file(&temporary, path)"));
    assert!(!vault_source.contains("fs::rename(&temporary_path, path)"));
    assert!(device_protection_source.contains("windows_dpapi_current_user"));
    assert!(!device_protection_source.contains("CRYPTPROTECT_LOCAL_MACHINE"));
    assert!(!wallet_adapter_source.contains("tauri::Window"));
    assert!(!wallet_adapter_source.contains("AppHandle"));
    assert!(wallet_adapter_source.contains("begin_operation"));
    assert!(wallet_adapter_source.contains("consume_recovery_path"));
    assert_eq!(
        wallet_adapter_production
            .match_indices(".run_authorized(")
            .count(),
        13
    );
    assert_eq!(
        wallet_adapter_production
            .match_indices("operation.complete(status)")
            .count(),
        3
    );
    assert!(!wallet_adapter_production.contains("activation_proof()"));
    assert!(!recovery_selection_source.contains("into_path()"));
    assert!(recovery_selection_source.contains("Some(FilePath::Path(path))"));
    assert!(recovery_selection_source.contains(".set_parent(window)"));
    assert!(recovery_selection_source.contains("FILE_ATTRIBUTE_REPARSE_POINT"));
    assert!(recovery_selection_source.contains("begin_recovery_path_selection"));
    assert!(recovery_selection_source.contains("complete_recovery_path_selection"));
    assert!(recovery_selection_source.contains("SelectionFailClosedGuard"));
    assert!(runtime_source.contains("impl Drop for RecoverySelectionPermit"));
    assert!(!secret_input_source.contains("#[tauri::command]"));
    assert!(!secret_input_source.contains("impl Serialize"));
    assert!(!secret_input_source.contains("impl<'de> Deserialize"));
    assert!(!secret_input_source.contains("serde_json"));
    assert!(!secret_input_source.contains("impl Clone"));
    assert!(!secret_input_source.contains("impl fmt::Debug"));
    assert!(!secrets_source.contains("SecretString"));
    assert!(secrets_source.contains("bytes: Zeroizing<Vec<u8>>"));
    assert!(secrets_source.contains("logical_len: usize"));
    assert!(!ceremony_source.contains("#[tauri::command]"));
    assert!(!ceremony_source.contains("wide_null(\"EDIT\")"));
    assert!(!ceremony_source.contains("wide_null(\"STATIC\")"));
    assert!(!ceremony_source.contains("GetWindowTextW"));
    assert!(!ceremony_source.contains("SetWindowTextW"));
    assert!(ceremony_production.contains("ImmAssociateContextEx(window, null_mut(), 0)"));
    assert!(ceremony_production.contains("ImmGetContext(window)"));
    assert!(ceremony_production.contains("ImmReleaseContext(window, context)"));
    assert!(ceremony_production.contains("disable_text_services(button)"));
    assert!(!ceremony_production.contains("IACE_CHILDREN"));
    assert!(!public_request_production.contains("#[tauri::command]"));
    assert!(!public_request_production.contains("password:"));
    assert!(!public_request_production.contains("owner_window:"));
    assert!(wallet_adapter_production.contains("request: WalletCreateRequest"));
    assert!(wallet_adapter_production.contains("request: WalletRestoreRequest"));
    assert!(!public_request_production.contains("derive(Debug, Deserialize)"));
    assert_eq!(
        capability_source.match_indices("allow-wallet-").count(),
        WALLET_COMMANDS.len()
    );
    assert!(!capability_source.contains("dialog:"));
    assert_eq!(
        wallet_exposure_source
            .match_indices("#[tauri::command]")
            .count(),
        WALLET_COMMANDS.len()
    );
    assert!(wallet_exposure_source.contains("WalletInvokeRequest<'_>"));
    assert!(!wallet_exposure_source.contains("SecretInput"));
    assert!(!wallet_exposure_source.contains("WalletSeed"));
    assert!(wallet_command_boundary_source.contains("native_recovery_selection"));
    assert!(wallet_command_boundary_source.contains("selected: true"));
    let core_api_source = read("../src/services/coreApi.ts");
    let wallet_panel_source = read("../src/features/wallet/WalletPanel.tsx");
    let wallet_types_source = read("../src/types/wallet.ts");
    let desktop_state_source = read("../src/state/desktopState.ts");
    let desktop_event_source = read("../src/events/desktopEvents.ts");
    assert!(core_api_source.contains("invoke<"));
    for command in WALLET_COMMANDS {
        assert!(core_api_source.contains(&format!("\"{command}\"")));
    }
    assert_eq!(
        core_api_source.match_indices("\"wallet_").count(),
        WALLET_COMMANDS.len()
    );
    for forbidden in [
        "type=\"password\"",
        "password:",
        "recovery_credential",
        "seed_phrase",
        "private_key",
        "signed_envelope",
        "signature:",
        "recovery_selection_handle",
        "recovery_destination_handle",
        "recovery_source_handle",
        "path_token",
        "localStorage",
        "sessionStorage",
        "navigator.clipboard",
    ] {
        assert!(!wallet_panel_source.contains(forbidden));
        assert!(!wallet_types_source.contains(forbidden));
        assert!(!core_api_source.contains(forbidden));
    }
    assert!(wallet_panel_source.contains("presentationEpochRef.current.invalidate()"));
    assert!(wallet_panel_source.contains("presentationEpochRef.current.isCurrent(epoch)"));
    assert!(wallet_panel_source.contains("presentationEpochRef.current.observeWindowBlur()"));
    assert!(wallet_panel_source.contains("presentationEpochRef.current.observeWindowFocus()"));
    assert_eq!(
        wallet_panel_source
            .match_indices("runWalletNativeSelectionWorkflow(")
            .count(),
        2
    );
    assert_eq!(
        wallet_panel_source.match_indices("catch (reason)").count(),
        wallet_panel_source
            .match_indices("failNativeOperation(reason, epoch);")
            .count()
    );
    assert!(!desktop_state_source.contains("WalletAccountState"));
    assert!(!desktop_event_source.contains("WalletAccountUpdated"));
    assert!(!read("../package.json").contains("@tauri-apps/plugin-dialog"));

    let support_command = command_source
        .split("fn generate_support_package_command")
        .nth(1)
        .and_then(|source| source.split("#[tauri::command]").next())
        .expect("support package helper has production source");
    assert!(!support_command.contains("tail_file"));
    assert!(!report_source.contains("WalkDir"));
    assert!(!report_source.contains("stdout_tail"));
    assert!(!report_source.contains("stderr_tail"));
    assert!(report_source.contains("EXPECTED_SUPPORT_FILES"));
    assert!(report_source.contains("FORBIDDEN_CONTENT_MARKERS"));
    assert!(report_source.contains("validate_support_files(&files)?"));
    assert!(report_source.contains("for support_file in &files"));
}

#[test]
fn wallet_sensitive_authority_requires_runtime_activation_proof() {
    let cargo_manifest = read("Cargo.toml");
    let activation_source = read("src/wallet/activation.rs");
    let kdf_source = read("src/wallet/kdf.rs");
    let lifecycle_source = read("src/wallet/lifecycle.rs");
    let ceremony_source = read("src/wallet/recovery_ceremony.rs");
    let lib_source = read("src/lib.rs");
    let runtime_source = read("src/wallet/runtime.rs");
    let onboarding_source = read("src/wallet/onboarding.rs");
    let recovery_source = read("src/wallet/recovery.rs");
    let secrets_source = read("src/wallet/secrets.rs");
    let session_source = read("src/wallet/session.rs");
    let transaction_source = read("src/wallet/transaction.rs");
    let vault_source = read("src/wallet/vault.rs");

    assert!(
        activation_source.contains("INDEPENDENT_LIFECYCLE_SECURITY_REVIEW_APPROVED: bool = true")
    );
    assert!(activation_source.contains("INDEPENDENT_SIGNING_SECURITY_REVIEW_APPROVED: bool = true"));
    assert!(
        activation_source.contains("INDEPENDENT_SUBMISSION_SECURITY_REVIEW_APPROVED: bool = true")
    );
    assert!(activation_source.contains("WalletActivationScope::Lifecycle"));
    assert!(activation_source.contains("WalletActivationScope::Signing"));
    assert!(activation_source.contains("WalletActivationScope::Submission"));
    assert!(activation_source.contains("WalletActivationScope::Reconciliation"));
    assert!(activation_source.contains("WalletActivationRequirement::IndependentSecurityReview"));
    assert!(runtime_source.contains("activation: WalletActivationPolicy"));
    assert_eq!(
        runtime_source
            .match_indices("self.require_activation(")
            .count(),
        4
    );
    assert!(runtime_source.contains("pub(in crate::wallet) struct WalletActivationProof"));
    assert_eq!(
        runtime_source
            .match_indices("activation_proof: WalletActivationProof {")
            .count(),
        5
    );
    assert!(runtime_source.contains("pub(in crate::wallet) fn promote_to_signing("));
    assert!(runtime_source.contains("if matches!("));
    assert!(runtime_source.contains("WalletOperationKind::Sign"));
    assert!(runtime_source.contains("WalletOperationKind::Submit"));
    assert!(runtime_source.contains("WalletOperationKind::Reconcile"));
    assert!(runtime_source.contains("WalletOperationKind::Refresh"));
    assert!(runtime_source.contains("return Err(WalletRuntimeError::InvalidRequest)"));
    assert!(runtime_source.contains("scope: WalletActivationScope"));
    assert!(runtime_source.contains("pub(in crate::wallet) fn require_signing"));
    assert!(runtime_source.contains("pub(in crate::wallet) fn require_submission"));
    assert!(runtime_source.contains("pub(in crate::wallet) fn require_reconciliation"));
    assert!(runtime_source.contains("activation_proof: WalletActivationProof"));
    assert!(runtime_source.contains("WalletRuntimeError::ActivationUnavailable"));
    assert!(cargo_manifest.contains("argon2 = { version = \"0.5.3\", features = [\"zeroize\"] }"));
    assert!(kdf_source.contains("hash_password_into_with_memory"));
    assert!(kdf_source.contains("impl Drop for Argon2Workspace"));
    assert!(kdf_source.contains("self.blocks.iter_mut().zeroize()"));
    assert!(!vault_source.contains("hash_password_into("));
    assert!(!recovery_source.contains("hash_password_into("));
    assert!(lib_source.contains("NativeRecoveryCredentialCeremony::new"));
    let ceremony_production = ceremony_source.split("#[cfg(test)]").next().unwrap();
    assert!(!ceremony_production.contains("#[tauri::command]"));
    assert!(!ceremony_production.contains("SetClipboardData"));
    assert!(!ceremony_production.contains("OpenClipboard"));
    assert!(!lifecycle_source.contains("WalletCreationResult"));
    assert!(transaction_source.contains(".require_signing()"));

    let create_flow = lifecycle_source
        .split("fn create_at(")
        .nth(1)
        .and_then(|source| source.split("pub(in crate::wallet) fn restore(").next())
        .expect("private create flow exists");
    let acknowledgement = create_flow
        .find("present_and_verify")
        .expect("native recovery acknowledgement is mandatory");
    let recovery_publication = create_flow
        .find("store_recovery_backup")
        .expect("recovery publication exists");
    let vault_publication = create_flow
        .find("store_local_vault")
        .expect("vault publication exists");
    assert!(acknowledgement < recovery_publication);
    assert!(recovery_publication < vault_publication);

    for source in [
        onboarding_source,
        recovery_source,
        secrets_source,
        session_source,
        transaction_source,
        vault_source,
    ] {
        assert!(source.contains("&WalletActivationProof"));
        assert!(!source.contains("WalletActivationProof {"));
        assert!(!source.contains("#[tauri::command]"));
    }
}
